sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_6f660444c5e3_key -iv $encrypted_6f660444c5e3_iv -in fifth-medley-347609-1e23ea5bb6b8.json.enc -out fifth-medley-347609-1e23ea5bb6b8.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file fifth-medley-347609-1e23ea5bb6b8.json
  - gcloud config set project fifth-medley-347609
  - gcloud config set compute/zone europe-west2-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t harryyy27/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true harryyy27/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master